### ISSUE TITLE
Category: Podcasts

### ISSUE THREAD

**Issue by HeidiHansen** [protect-earth/protect.earth#22]
People fixing the world, BBC World Service
Democracy now
The Energy Transition Show
Talking Headways: stories on sustainable transportation, urban planning, and economic development

Also, do we want to link to particular episodes of more general podcasts, e.g. The Radiolab podcast that discusses wastewater treatment?

**Comment by philsturgeon** [comment]
https://www.youvebeenwarmed.com/

https://open.spotify.com/show/5rt2DC1hDOsMgW3P2Uxdan

http://www.sustainababble.fish/

https://climate.mit.edu/users/tilclimate-podcast
