### ISSUE TITLE
Submission Form

### ISSUE THREAD

**Issue by philsturgeon** [protect-earth/protect.earth#29]
**Updated (2020-10-22):** Now that we're going with Airtable and getting rid of a lot of code, can we see if any of these form solutions will help us add suggestions from the public and let us moderate them?

- https://beenform.co/
- https://builtonair.com/resource/airtable-proxy-cloudflare-worker/
- https://builtonair.com/resource/form-nano/
- https://builtonair.com/resource/airconnex/
- https://builtonair.com/resource/on2air-forms-2/

I don't know anything about them but any one of them could probably do the job.

**Comment by ijpatricio** [comment]
I also prefer using Statamic forms. 
Database wise... Do we have a vps, or how is it setup??

Also, we could just post the form data into a GoogleSheet. From the backend, with honeypot check, csrf etc.

**Comment by philsturgeon** [comment]
Netlify is basically a Google Sheet so it might be the better choice for now. Remember, the frontend is netlify and the backend is basically a VPS on Digital Ocean, and getting stuff out of there is a bit of a pain in the butt. We will, in time, use Spock which will commit back CP changes but meh, maybe lets use Netlify forms for now so we dont have to think about any security or anything.

**Comment by philsturgeon** [comment]
Let's make this on a `/suggest` page or something like that. In v1 it went into About and that might be a little hard for folks to find.
