### ISSUE TITLE
Crop Category Images for Homepage

### ISSUE THREAD

**Issue by ijpatricio** [protect-earth/protect.earth#35]

**Comment by philsturgeon** [comment]
There should be a way in Statamic Content API to request smaller versions of the images. They use Glide, which is designed to do just that. I've made https://github.com/statamic/docs/issues/100 which might end up being a feature request if the functionality is not currently possible.  [Assets](https://statamic.dev/assets#image-manipulation) do support image manipulation via glide for the feontend, so its likely. 

We can hack it if we need to, leave it with me.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67381/78557446-b8940000-7808-11ea-8a0f-cb08d7256e0a.png">

Noticed a funny issue loading with a slow connection:

**Comment by ijpatricio** [comment]
Ooooh great! it will be adding query_params on href, or making a scr-set, i guess!

Nevermind, I'll take care of this, go with other topics that i can't address.

**Comment by philsturgeon** [comment]
Update on my question to Statamic. Seems like they've got a workaround https://github.com/statamic/ideas/issues/127#issuecomment-610029237
