### ISSUE TITLE
Recent Items 

### ISSUE THREAD

**Issue by ijpatricio** [protect-earth/protect.earth#37]
On the Hero 3 cards would it be great, instead of a list???

**Comment by ijpatricio** [comment]
@philsturgeon what do you think of the recent links not being a list, but instead making use of those 3 cards?

or instead of 3 column cards, wide cars , one per row... 

lmk your thoughts!

**Comment by philsturgeon** [comment]
Sounds good. We can tie up the icons to #12 in the future, maybe comment them out for now. we need a header saying "New Actions to Try" or something.

**Comment by philsturgeon** [comment]
OH duh the icons can just be for "categories". :D LMK if you need help picking them.

**Comment by philsturgeon** [comment]
@ijpatricio the API endpoint for getting recent items is: `https://api.protect.earth/api/collections/actions/entries/?sort=-date`

**Comment by ijpatricio** [comment]
@philsturgeon did you check already the 3 cards on the homepage??

I put it already from that endpoint, limiting to 3 and filtered by `published` status on the cms end.

Am I missing something?

PS: Days have been tight lately. With smaller PR's from now will be easier to push forward

```
getRecentActions(amount = 3) {

    const queryParams = `filter[status:equals]=published&limit=${amount}&sort=-date`

    return fetch(`${baseApiUrl}/api/collections/actions/entries?${queryParams}`)
      .then(r => r.json())
  },
```

**Comment by philsturgeon** [comment]
Great! Closing.
