### ISSUE TITLE
Tag Page

### ISSUE THREAD

**Issue by philsturgeon** [protect-earth/protect.earth#49]
We've got some links in the footer to `/tags` but that's not going to be a page. We'll only have landing pages for tags, populating things like the `I am a...` dropdown #36 and as a precursor to more formal #12.

Let's get `/tags/land-owner` looking a bit more like https://protect.earth/tags/land-owner.

**Comment by philsturgeon** [comment]
@imkieransmith do you think you could knock this one out too? It's basically the same thing but tags this time! :D

**Comment by mbifulco** [comment]
@philsturgeon funny enough I just pulled up this issue, and the `land-owner` url is... gone?

This one works though https://protect.earth/tags/business

**Comment by philsturgeon** [comment]
https://protect.earth/tags/land-owners oops

**Comment by mbifulco** [comment]
Ah I see! we link to land-owner in nav right now 😬

**Comment by philsturgeon** [comment]
Right right sorry I was fixing that.

---
Phil Sturgeon
🌍 [Saving the world](https://protect.earth/) and 🚴‍♂️ [crashing bikes](https://phil.bike)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
