### ISSUE TITLE
Track outgoing Action clicks

### ISSUE THREAD

**Issue by philsturgeon** [protect-earth/protect.earth#50]
We don't want anything super snoopy like Google Analytics but we do wanna know how many people are going out to which links so we can rank popularity and maybe _maybe_ allow paid placements to help us pay back contributors some day, or buy more trees, or something. 

Regardless, knowing if anyone is actually clicking these links would be pretty great. 

Netlify analytics is a bit useless and only tells you who is hitting frontend links, so we could maybe make an outgoing redirect in Netlify but... egh.

Could be done through a Statamic plugin if those exist, or just some plain old frontend JavaScript. 

Suggestions on a postcard and PRs please!

**Comment by william-woodhead** [comment]
It seems to me like there are 4 options:

1. Use a link shortening 3rd party service like bitly or rebrandly
1. Use a plugin for statamic
1. Use GA or equivalent to track clicks
1. Create our own datastore and send clicks to our own endpoint.

#### **Use a link shortening service Like bitly or rebrandly**

**pros:**
- very easy to set up
- analytics out of the box
- free tier

**cons:**
- will have to create a shortened link every time we create a new link
- lots of traffic will cost

#### **Use GA or equivalent to track clicks**

**pros:**
- free tier
- simple setup
- analytics out of the box

**cons:**
- google have a lot of data about your site

#### **Plugin for statamic**
(I could not find a suitable plugin when I took a cursory glance)

#### **Create our own datastore and endpoint**

eg. Use netlify function and an airtable/firebase table

**pros:**
- price will remain low
- we have complete control of the data

**cons:**
- more time to setup
- more services to maintain
- no fancy analytics out of the box

**Comment by mbifulco** [comment]
A reasonable GA-alternative is [fathom](https://github.com/usefathom/fathom#lite-vs-pro) - their OSS model is self-hostable, and I think would easily fit in a free-tier heroku dyno.

**Comment by philsturgeon** [comment]
We've also got Digital Ocean so we could host fathom on a cheapy $5 thing. I'm still trying to bug DO to get us some credits/freeness. https://marketplace.digitalocean.com/apps/fathom-analytics

Having Netlify AND Forge AND Digital Ocean AND Heroku might be a step too far.

**Comment by william-woodhead** [comment]
Had a look at Fathom and it looks as though the only custom events you can send are called Goals. So it would mean setting up each external link as an individual Goal, and then adding a bit of javascript to send the Goal event before navigating to the external link. https://usefathom.com/support/goals .

**Comment by philsturgeon** [comment]
Oh man creating ids from the dashboard doesn’t seem like a fun time, again unless we can make an extension for statamic or something which gives it a fathom ID when they’re added. That seems like a lot of work, probably not worth it.

Do we have to use GA? 😞

**Comment by philsturgeon** [comment]
Aha, Matomo it is. I’ll set up a Digital Ocean https://matomo.org/faq/new-to-piwik/faq_71/

**Comment by philsturgeon** [comment]
According to @mbifulco, [Fathom](https://usefathom.com/) is adding outgoing link tracking, which we can use to avoid writing any code or messing about.

**Comment by philsturgeon** [comment]
@mbifulco did Fathom get this feature out? :)
