### ISSUE TITLE
React Component for Actions

### ISSUE THREAD

**Issue by philsturgeon** [protect-earth/protect.earth#51]
Let's create a React/Web Component to let people pull content from our API. 

For example, a list of "Food" actions in the UK.

We can use this on sites like:

https://climatechoice.co/change-how-you-eat

This is a general guide which lacks calls to action, so we can suggest 10 actual services or things for them. 

### Implementation

The API is generated by [Statamic Content API](https://statamic.dev/rest-api) which is hosted over here: https://api.protect.earth/api/collections/actions/entries/

~There is one small issue: pulling out entries by category does not seem to be an option at the moment. We might want to OSS that in, so we need a PHP person to pick this up. https://github.com/statamic/ideas/issues/138~

**Comment by ofpiyush** [comment]
Sample: https://api.protect.earth/api/collections/actions/entries/?filter[categories:contains]=a1a4ac88-627d-4bc7-a5b5-d3dcdc10cc43

**Comment by philsturgeon** [comment]
HA! Ok awesome, I am a dummy. I just had to use the category ID not the category slug.

Maybe we can just do two queries, and let people get all the category data, then get the actions.

**Comment by ofpiyush** [comment]
Underneath, it runs a `like` query though. Might want to make another API endpoint instead of using this one OR as the content doesn't change much, setup caching when scale hits.

**Comment by philsturgeon** [comment]
We've not created any endpoints and we can't actually do that, it's a generated API from the Statamic CMS: https://statamic.dev/rest-api
