### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by philsturgeon** [protect-earth/protect.earth#54]
Part of the v2 launch will be a fantastic redesign. I've shared the wireframes with a few people, let me know if you need them.

The job can either be to create visual static HTML and we'll figure out how to Vue.js'ify it, or it can be done as a pull request to the repo. We can work with any process.

**Comment by ofpiyush** [comment]
Can you attach the new design and intended user flows here?

**Comment by philsturgeon** [comment]
Sent the wireframes to everyone on slack. :)

**Comment by philsturgeon** [comment]
Found somebody to get this done! Let’s keep this as a place for updates.
