### ISSUE TITLE
Get homepage closer to wireframes

### ISSUE THREAD

**Issue by ijpatricio** [protect-earth/protect.earth#55]
"What can we Do?" was added to v1, but could be moved over to v2, along with some of the newer sections.

<img width="634" alt="image" src="https://user-images.githubusercontent.com/67381/81215722-a78a0a80-8fd1-11ea-803d-bbd66d77c7a9.png">

See all the new wireframes here: https://balsamiq.cloud/s9t5ox1/p41eefe

**Comment by philsturgeon** [comment]
If we can get home, categories and tags pages looking a bit like this we're onto a huge winner.

**Comment by philsturgeon** [comment]
I've updated the scope of this issue a bit. Don't worry about doing 100%, just get the homepage closer to the wireframes.

These can go in without a huge amount of styling, they just need to be there functionally so the does stuff.

- [ ] What can we do?
- [ ] Does this apply to me?
- [ ] Find your action!
