### ISSUE TITLE
Actions by Category Page

### ISSUE THREAD

**Issue by philsturgeon** [protect-earth/protect.earth#57]
Keeping [the wireframes](https://balsamiq.cloud/s9t5ox1/p41eefe/r67D2) in mind, we could do with category pages:

- Carbon Reduction
- Food
- Politics

etc.

They must match the old URLs:

- protect.earth/carbon-reduction
- protect.earth/food
- protect.earth/politics

The API endpoint is this: https://api.protect.earth/api/collections/categories/entries/

You can skip the fancy featured image bit as that'll be done in #40, and don't worry about all the fancy filters bit either, we just need to get an MVP up.

**Comment by imkieransmith** [comment]
I'm working on this. Aiming to have something to show soon.

**Comment by philsturgeon** [comment]
Done!
