### ISSUE TITLE
Instructions in readme.md

### ISSUE THREAD

**Issue by johnrhunt** [protect-earth/protect.earth#87]
As someone who wants to help but doesn't do the javascript thing - it would be useful to know how I can compile the project (or whatever it needs..) for local development. My suggestion is some simple notes in the readme.md.

**Comment by philsturgeon** [comment]
We've got https://github.com/protect-earth/protect.earth/blob/master/CONTRIBUTING.md explaining where links data is. 

We're rewriting the site so no work on features or documentation is being done to describe the current website.
