### ISSUE TITLE
Search (with filters)

### ISSUE THREAD

**Issue by philsturgeon** [protect-earth/protect.earth#9]
Implement a search page `/search` in the new frontend (found in the `new` branch). Our amazing [new backend has search functionality](https://statamic.dev/search) which integrates with Algolia. 

This means we can just use the [JavaScript frontend client](https://www.algolia.com/doc/api-client/getting-started/install/javascript/?language=javascript), and the search key is `e8be8c8a25143890d82abf2108de8f93`.

Please hook up the search form in the header:

<img width="382" alt="image" src="https://user-images.githubusercontent.com/67381/78565674-2a267b00-7816-11ea-9ab9-d04dc951fe39.png">

I think our Algolia integration only sends the `title` and `id` property, so if you're feeling adventurous you could try and get it sending tags and description, to make search find those results too, but... by no means feel obligated. 

Poke me for API keys.

**Comment by philsturgeon** [comment]
Ok! We're going with Statamic for the rewrite, which looks like it [handles search nicely](https://statamic.dev/search). it's going to be API driven (#1) and Statamic have Algolia search built right in. 

I've mentioned this in the #6 @ijpatricio, and I'll try and get this sorted out in the `api` branch shortly.

**Comment by philsturgeon** [comment]
Statamic conversion complete! #13 

Algolia has been hooked up: 1c888a5

If anyone can pick this up, base off of the `feature/frontend` branch, use the [JavaScript frontend client](https://www.algolia.com/doc/api-client/getting-started/install/javascript/?language=javascript), and the search key is `e8be8c8a25143890d82abf2108de8f93`.

**Comment by Squallac** [comment]
I can work on this @philsturgeon

**Comment by philsturgeon** [comment]
@Squallac this is in progress, I just poked the chat to get him to accept the invite and assign it to himself. Would you be interested in working on #28?

**Comment by Squallac** [comment]
Yeah, sounds good @philsturgeon

**Comment by philsturgeon** [comment]
Gonna call this one done even though its not designed yet. Thanks @Tajmaha!
