### ISSUE TITLE
Switch to gatsby-source-airtable

### ISSUE THREAD

**Issue by philsturgeon** [protect-earth/protect.earth#93]
Giving up on the big v2, we're making incremental improvements that solve the same problems: 

1. Other sites able to access our dataset
2. Folks can submit links without messing with YAML
3. Moderators don't need to mess with this at a GitHub level

We've migrated our entire data set to Airtable, so now we just need to hook it up. 

https://www.gatsbyjs.com/plugins/gatsby-source-airtable/

Shouldn't be all that much different from the existing YAML source, as the fields are data structure is still the same.

**Comment by SOHELAHMED7** [comment]
Hi Phil,

I am the one who commented: https://twitter.com/SohelAhmedM/status/1319979992827056128

**Comment by SOHELAHMED7** [comment]
Before proceeding I would like to clear my doubts. Which way you have decided to go with? 1. Gastby Airtable plugin or 2. Gary's suggested way (https://twitter.com/philsturgeon/status/1319240136220200962) to create HTTP function on Lambda and give data of  Airbable from there?

**Comment by SOHELAHMED7** [comment]
If you choose 1st way you can invite me on Airtable. My email address can be found at https://github.com/sohelahmed7 

I can go through table and can get Airtable API key

**Comment by philsturgeon** [comment]
@SOHELAHMED7 I've just asked @GeeH to knock up the lambda so as soon as it's ready I'll give you the URL.

**Comment by SOHELAHMED7** [comment]
@philsturgeon  Out of curiosity what is the purpose of setting AWS Lambda HTTP function on the top of Airtable API to read data from Airtable. Why don't read data directly from Airtable API by https://www.gatsbyjs.com/plugins/gatsby-source-airtable/

**Comment by SOHELAHMED7** [comment]
Hi @philsturgeon 

Created PR -> https://github.com/protect-earth/protect.earth/pull/96

Let me know if sorting needs any changes or addition:

https://github.com/protect-earth/protect.earth/pull/96/files#diff-7d335d9933a2a7bd080525968146ecbe3728a087fc5835a439dad04beba2435aR141

**Comment by SOHELAHMED7** [comment]
Also 

At Line https://github.com/protect-earth/protect.earth/blob/main/src/pages/select-your-country.jsx#L73

data should be fetched from AirTable, right?

If yes, do I have to filter by status "Completed"?

**Comment by philsturgeon** [comment]
Good question! I fixed it up, it wasn't even being used.
