### ISSUE TITLE
Site Status?

### ISSUE THREAD

**Issue by jpsingleton** [protect-earth/protect.earth#95]
Not sure if I missed something but when I go to [protect.earth](https://www.protect.earth/) it's just a landing page with an email sign-up form. Where did all the content go?

**Comment by jpsingleton** [comment]
Looks like you can still get to the site at https://protect-earth.netlify.app/

**Comment by philsturgeon** [comment]
It's over here: https://actions.protect.earth

We've had a huge pivot and are switching to direct action, we're planting trees all over the UK and buying land too. 

https://www.patreon.com/ProtectEarth

The site is being reworked to match this, and we're working with folks like ClimateChoice.co to see if we can migrate our content over to them.
